--- 
clone: 
  depth: 1
kind: pipeline
name: EvaPipeline
steps: 
  - name: Kernel Pipeline
    image: archlinux:base-devel
    commands: 
      - curl -fsSL "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" | bsdtar -C / -xvf -
      - pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python2 python zip
      - export LANG=C && export LC_ALL=en_US.UTF-8
      - "export token=$TOKEN"
      - "bash build.sh"
  - name: Publish
    image: plugins/github-release
    settings:
      api_key:
         from_secret: github_token
      files: AnyKernel/CartelProject*
      title: Beta1
    when: 
      event: tag
